name: '🐛 Bug Report'
description: 'Report a bug or issue with the Orcfax Archive Viewer'
title: 'Bug: '
labels: ['bug-report']
body:
  - type: markdown
    attributes:
      value: |
        ----

        # Bug Description

  - type: textarea
    id: bug-steps
    attributes:
      label: What are the steps to reproduce this issue?
      placeholder: |
        1. Click on '...'
        2. Scroll down to '...'
        3. …
        4. See error
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happens?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: What were you expecting to happen?
      description: A clear and concise description of what was supposed to happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ----

        # Additional Context

  - type: input
    id: operating-system
    attributes:
      label: What is your OS? (include version)
      placeholder: 'e.g. macOS 14.6.1, Android 15'
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: What is your Browser? (include version)
      placeholder: 'e.g. Chrome 129.0.6668.58, Safari 18.0'
    validations:
      required: true

  - type: textarea
    id: bug-context
    attributes:
      label: Anything else?
      description: Add any other context you can provide about the problem here.
